### ISSUE TITLE
Log export fails with '413 Request Entity Too Large' status code

### ISSUE THREAD

**Issue by julealgon** [open-telemetry/opentelemetry-collector-contrib#16834]
### Component(s)

exporter/datadog

## Description

I've observed one of our applications has stopped pushing logs via the collector, and then double checked the error log in the VM running the collector.

It appears to be failing with a `413 Request Entity Too Large` error, retrying multiple times, and then discarding the data.

## Steps to Reproduce

Unknown at this point what is causing this.

## Expected Result

No exceptions and logs flowing through to datadog.

## Actual Result

Logs are not flowing for this particular application.

### Collector version

0.62.1

## Environment
OS: (e.g., "Windows Server 2019 DataCenter 10.0.17763.3650")

### OpenTelemetry Collector configuration

```yaml
receivers:
  otlp:
    protocols:
      grpc:

  hostmetrics:
    collection_interval: 10s
    scrapers:
      paging:
        metrics:
          system.paging.utilization:
            enabled: true
      cpu:
        metrics:
          system.cpu.utilization:
            enabled: true
      disk:
      filesystem:
        metrics:
          system.filesystem.utilization:
            enabled: true
      load:
      memory:
      network:
      processes:

processors:
  batch:
    timeout: 10s

  resource:
    attributes:
    - key: deployment.environment
      value: "beta"
      action: upsert

exporters:
  datadog:
    api:
      key: ${DATADOG_APIKEY}

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [resource, batch]
      exporters: [datadog]
    metrics:
      receivers: [hostmetrics, otlp]
      processors: [resource, batch]
      exporters: [datadog]
    logs:
      receivers: [otlp]
      processors: [resource, batch]
      exporters: [datadog]
```

### Log output

```shell
2022-12-09T16:05:07.076Z	info	exporterhelper/queued_retry.go:427	Exporting failed. Will retry the request after interval.	{"kind": "exporter", "data_type": "logs", "name": "datadog", "error": "413 Request Entity Too Large", "interval": "18.341313917s"}
2022-12-09T16:05:14.630Z	error	logs/sender.go:68	Failed to send logs	{"kind": "exporter", "data_type": "logs", "name": "datadog", "error": "413 Request Entity Too Large", "msg": "{\"errors\":[{\"status\":\"413\",\"title\":\"Request Entity Too Large\",\"detail\":\"Request too large\"}]}", "status_code": "413 Request Entity Too Large"}
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/datadogexporter/internal/logs.(*Sender).SubmitLogs
	github.com/open-telemetry/opentelemetry-collector-contrib/exporter/datadogexporter@v0.62.0/internal/logs/sender.go:68
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/datadogexporter.(*logsExporter).consumeLogs
	github.com/open-telemetry/opentelemetry-collector-contrib/exporter/datadogexporter@v0.62.0/logs_exporter.go:101
go.opentelemetry.io/collector/exporter/exporterhelper.(*logsRequest).Export
	go.opentelemetry.io/collector@v0.62.1/exporter/exporterhelper/logs.go:65
go.opentelemetry.io/collector/exporter/exporterhelper.(*timeoutSender).send
	go.opentelemetry.io/collector@v0.62.1/exporter/exporterhelper/common.go:203
go.opentelemetry.io/collector/exporter/exporterhelper.(*retrySender).send
	go.opentelemetry.io/collector@v0.62.1/exporter/exporterhelper/queued_retry.go:388
go.opentelemetry.io/collector/exporter/exporterhelper.(*logsExporterWithObservability).send
	go.opentelemetry.io/collector@v0.62.1/exporter/exporterhelper/logs.go:132
go.opentelemetry.io/collector/exporter/exporterhelper.(*queuedRetrySender).start.func1
	go.opentelemetry.io/collector@v0.62.1/exporter/exporterhelper/queued_retry.go:206
go.opentelemetry.io/collector/exporter/exporterhelper/internal.(*boundedMemoryQueue).StartConsumers.func1
	go.opentelemetry.io/collector@v0.62.1/exporter/exporterhelper/internal/bounded_memory_queue.go:61
2022-12-09T16:05:25.629Z	error	logs/sender.go:68	Failed to send logs	{"kind": "exporter", "data_type": "logs", "name": "datadog", "error": "413 Request Entity Too Large", "msg": "{\"errors\":[{\"status\":\"413\",\"title\":\"Request Entity Too Large\",\"detail\":\"Request too large\"}]}", "status_code": "413 Request Entity Too Large"}
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/datadogexporter/internal/logs.(*Sender).SubmitLogs
	github.com/open-telemetry/opentelemetry-collector-contrib/exporter/datadogexporter@v0.62.0/internal/logs/sender.go:68
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/datadogexporter.(*logsExporter).consumeLogs
	github.com/open-telemetry/opentelemetry-collector-contrib/exporter/datadogexporter@v0.62.0/logs_exporter.go:101
go.opentelemetry.io/collector/exporter/exporterhelper.(*logsRequest).Export
	go.opentelemetry.io/collector@v0.62.1/exporter/exporterhelper/logs.go:65
go.opentelemetry.io/collector/exporter/exporterhelper.(*timeoutSender).send
	go.opentelemetry.io/collector@v0.62.1/exporter/exporterhelper/common.go:203
go.opentelemetry.io/collector/exporter/exporterhelper.(*retrySender).send
	go.opentelemetry.io/collector@v0.62.1/exporter/exporterhelper/queued_retry.go:388
go.opentelemetry.io/collector/exporter/exporterhelper.(*logsExporterWithObservability).send
	go.opentelemetry.io/collector@v0.62.1/exporter/exporterhelper/logs.go:132
go.opentelemetry.io/collector/exporter/exporterhelper.(*queuedRetrySender).start.func1
	go.opentelemetry.io/collector@v0.62.1/exporter/exporterhelper/queued_retry.go:206
go.opentelemetry.io/collector/exporter/exporterhelper/internal.(*boundedMemoryQueue).StartConsumers.func1
	go.opentelemetry.io/collector@v0.62.1/exporter/exporterhelper/internal/bounded_memory_queue.go:61
2022-12-09T16:05:25.629Z	error	exporterhelper/queued_retry.go:176	Exporting failed. No more retries left. Dropping data.	{"kind": "exporter", "data_type": "logs", "name": "datadog", "error": "max elapsed time expired 413 Request Entity Too Large", "dropped_items": 6604}
go.opentelemetry.io/collector/exporter/exporterhelper.(*queuedRetrySender).onTemporaryFailure
	go.opentelemetry.io/collector@v0.62.1/exporter/exporterhelper/queued_retry.go:176
go.opentelemetry.io/collector/exporter/exporterhelper.(*retrySender).send
	go.opentelemetry.io/collector@v0.62.1/exporter/exporterhelper/queued_retry.go:411
go.opentelemetry.io/collector/exporter/exporterhelper.(*logsExporterWithObservability).send
	go.opentelemetry.io/collector@v0.62.1/exporter/exporterhelper/logs.go:132
go.opentelemetry.io/collector/exporter/exporterhelper.(*queuedRetrySender).start.func1
	go.opentelemetry.io/collector@v0.62.1/exporter/exporterhelper/queued_retry.go:206
go.opentelemetry.io/collector/exporter/exporterhelper/internal.(*boundedMemoryQueue).StartConsumers.func1
	go.opentelemetry.io/collector@v0.62.1/exporter/exporterhelper/internal/bounded_memory_queue.go:61
```

### Additional context

Nothing relevant at this point.

**Comment by julealgon** [comment]
I initially had a suspicion that this could've been caused by a couple of recent changes we did to the application:
- migrated from .NET6 to .NET7
- updated every single dependency to latest versions
- added service name and namespace, as well as OtelSDK info (were missing before)

However, I used a separate sample application here that I use for testing purposes and did the exact same steps with it. Then, I added the exact same service information that I added to the original application, and I can see the traces in Datadog.

I'm completely lost now as to what could be the root cause of this.

I'll try to disable instrumentations one by one to see if that might be related in any way.

**Comment by dineshg13** [comment]
@julealgon can you please try with the latest `v0.67.0`   version of collector. This was fixed in https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/16380.

**Comment by julealgon** [comment]
> @julealgon can you please try with the latest `v0.67.0` version of collector. This was fixed in #16380.

@dineshg13  I will try updating today along with a few other tests. However, are you sure this was fixed as part of #16380? I actually did find that issue before opening this one, but they have different HTTP status codes. Looks like that one is talking about the URL, while mine is caused by payload size.

**Comment by julealgon** [comment]
@dineshg13 after updating to latest (0.67.0), I'm now not seeing any errors in the collector console but no logs are coming at all from the application.

If I push logs from my local environment instead, I see them as before.

I have no idea what is going on here. I'm pushing from local using the exact same application/version as I'm using in Azure.

I'm now wondering if this is something about the Azure .NET7 AppService environment that is causing the issue. Just in case, I'll try updating every OTEL .NET library to their latest beta versions and redeploy the app.

**Comment by julealgon** [comment]
Ok, after further testing, I can confirm this does not seem to be an Azure-specific connection issue: after adding a `file` exporter, I can actually see data being logger there for my service.

It appears that scope information is completely missing however. All the logs inside the scope are intact, but the scope itself (the tracing main data) is not there so it does not exist in Datadog as well.

Here is the output I saw from making a single request to my application (I've redacted some of the info):
```json
{
    "resourceLogs": [{
            "resource": {
                "attributes": [{
                        "key": "service.name",
                        "value": {
                            "stringValue": "REDACTED"
                        }
                    }, {
                        "key": "service.namespace",
                        "value": {
                            "stringValue": "REDACTED"
                        }
                    }, {
                        "key": "service.instance.id",
                        "value": {
                            "stringValue": "5e334c5e-5ef0-4c8c-80f4-ebf9a93d2d8b"
                        }
                    }, {
                        "key": "telemetry.sdk.name",
                        "value": {
                            "stringValue": "opentelemetry"
                        }
                    }, {
                        "key": "telemetry.sdk.language",
                        "value": {
                            "stringValue": "dotnet"
                        }
                    }, {
                        "key": "telemetry.sdk.version",
                        "value": {
                            "stringValue": "1.3.1.622"
                        }
                    }, {
                        "key": "deployment.environment",
                        "value": {
                            "stringValue": "beta"
                        }
                    }
                ]
            },
            "scopeLogs": [{
                    "scope": {},
                    "logRecords": [{
                            "timeUnixNano": "1670858470630743200",
                            "severityNumber": 9,
                            "severityText": "Information",
                            "body": {
                                "stringValue": "IDX10242: Security token: '[PII of type 'System.String' is hidden. For more details, see https://aka.ms/IdentityModel/PII.]' has a valid signature."
                            },
                            "attributes": [{
                                    "key": "dotnet.ilogger.category",
                                    "value": {
                                        "stringValue": "Microsoft.IdentityModel.LoggingExtensions.IdentityLoggerAdapter"
                                    }
                                }
                            ],
                            "traceId": "ddaa4e9c5a223c774e0b3817d88d173e",
                            "spanId": "86430313a5338a30"
                        }, {
                            "timeUnixNano": "1670858470630840500",
                            "severityNumber": 9,
                            "severityText": "Information",
                            "body": {
                                "stringValue": "IDX10239: Lifetime of the token is valid."
                            },
                            "attributes": [{
                                    "key": "dotnet.ilogger.category",
                                    "value": {
                                        "stringValue": "Microsoft.IdentityModel.LoggingExtensions.IdentityLoggerAdapter"
                                    }
                                }
                            ],
                            "traceId": "ddaa4e9c5a223c774e0b3817d88d173e",
                            "spanId": "86430313a5338a30"
                        }, {
                            "timeUnixNano": "1670858470630929700",
                            "severityNumber": 9,
                            "severityText": "Information",
                            "body": {
                                "stringValue": "IDX10234: Audience Validated.Audience: 'api://REDACTED'"
                            },
                            "attributes": [{
                                    "key": "dotnet.ilogger.category",
                                    "value": {
                                        "stringValue": "Microsoft.IdentityModel.LoggingExtensions.IdentityLoggerAdapter"
                                    }
                                }
                            ],
                            "traceId": "ddaa4e9c5a223c774e0b3817d88d173e",
                            "spanId": "86430313a5338a30"
                        }, {
                            "timeUnixNano": "1670858470630982500",
                            "severityNumber": 9,
                            "severityText": "Information",
                            "body": {
                                "stringValue": "IDX10245: Creating claims identity from the validated token: '[PII of type 'System.IdentityModel.Tokens.Jwt.JwtSecurityToken' is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'."
                            },
                            "attributes": [{
                                    "key": "dotnet.ilogger.category",
                                    "value": {
                                        "stringValue": "Microsoft.IdentityModel.LoggingExtensions.IdentityLoggerAdapter"
                                    }
                                }
                            ],
                            "traceId": "ddaa4e9c5a223c774e0b3817d88d173e",
                            "spanId": "86430313a5338a30"
                        }, {
                            "timeUnixNano": "1670858470631025800",
                            "severityNumber": 9,
                            "severityText": "Information",
                            "body": {
                                "stringValue": "IDX10241: Security token validated. token: '[PII of type 'System.String' is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'."
                            },
                            "attributes": [{
                                    "key": "dotnet.ilogger.category",
                                    "value": {
                                        "stringValue": "Microsoft.IdentityModel.LoggingExtensions.IdentityLoggerAdapter"
                                    }
                                }
                            ],
                            "traceId": "ddaa4e9c5a223c774e0b3817d88d173e",
                            "spanId": "86430313a5338a30"
                        }
                    ]
                }
            ]
        }
    ]
}
```

Notice how all logs have the trace/span IDs, but scope info is missing entirely:

```json
            "scopeLogs": [{
                    "scope": {},
```

**Comment by julealgon** [comment]
@dineshg13 , I'm seeing the 413 error again right now, using latest collector:

```
2022-12-12T16:05:48.309Z	error	logs/sender.go:84	Failed to send logs	{"kind": "exporter", "data_type": "logs", "name": "datadog", "error": "413 Request Entity Too Large", "msg": "{\"errors\":[{\"status\":\"413\",\"title\":\"Request Entity Too Large\",\"detail\":\"Request too large\"}]}", "status_code": "413 Request Entity Too Large"}
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/datadogexporter/internal/logs.(*Sender).SubmitLogs
	github.com/open-telemetry/opentelemetry-collector-contrib/exporter/datadogexporter@v0.67.0/internal/logs/sender.go:84
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/datadogexporter.(*logsExporter).consumeLogs
	github.com/open-telemetry/opentelemetry-collector-contrib/exporter/datadogexporter@v0.67.0/logs_exporter.go:101
go.opentelemetry.io/collector/exporter/exporterhelper.(*logsRequest).Export
	go.opentelemetry.io/collector@v0.67.0/exporter/exporterhelper/logs.go:65
go.opentelemetry.io/collector/exporter/exporterhelper.(*timeoutSender).send
	go.opentelemetry.io/collector@v0.67.0/exporter/exporterhelper/common.go:208
go.opentelemetry.io/collector/exporter/exporterhelper.(*retrySender).send
	go.opentelemetry.io/collector@v0.67.0/exporter/exporterhelper/queued_retry.go:387
go.opentelemetry.io/collector/exporter/exporterhelper.(*logsExporterWithObservability).send
	go.opentelemetry.io/collector@v0.67.0/exporter/exporterhelper/logs.go:135
go.opentelemetry.io/collector/exporter/exporterhelper.(*queuedRetrySender).start.func1
	go.opentelemetry.io/collector@v0.67.0/exporter/exporterhelper/queued_retry.go:205
go.opentelemetry.io/collector/exporter/exporterhelper/internal.(*boundedMemoryQueue).StartConsumers.func1
	go.opentelemetry.io/collector@v0.67.0/exporter/exporterhelper/internal/bounded_memory_queue.go:61
2022-12-12T16:05:48.309Z	error	exporterhelper/queued_retry.go:175	Exporting failed. No more retries left. Dropping data.	{"kind": "exporter", "data_type": "logs", "name": "datadog", "error": "max elapsed time expired 413 Request Entity Too Large", "dropped_items": 8266}
go.opentelemetry.io/collector/exporter/exporterhelper.(*queuedRetrySender).onTemporaryFailure
	go.opentelemetry.io/collector@v0.67.0/exporter/exporterhelper/queued_retry.go:175
go.opentelemetry.io/collector/exporter/exporterhelper.(*retrySender).send
	go.opentelemetry.io/collector@v0.67.0/exporter/exporterhelper/queued_retry.go:410
go.opentelemetry.io/collector/exporter/exporterhelper.(*logsExporterWithObservability).send
	go.opentelemetry.io/collector@v0.67.0/exporter/exporterhelper/logs.go:135
go.opentelemetry.io/collector/exporter/exporterhelper.(*queuedRetrySender).start.func1
	go.opentelemetry.io/collector@v0.67.0/exporter/exporterhelper/queued_retry.go:205
go.opentelemetry.io/collector/exporter/exporterhelper/internal.(*boundedMemoryQueue).StartConsumers.func1
	go.opentelemetry.io/collector@v0.67.0/exporter/exporterhelper/internal/bounded_memory_queue.go:61
```

Still not seeing any traces after bumping every single OTEL library to their latest versions.

**Comment by julealgon** [comment]
I figured why I was not seeing tracing info and it was due to something else entirely:
- https://github.com/open-telemetry/opentelemetry-dotnet/issues/3753

I'll still leave this one open since the 413 responses are still happening, even if they are unrelated to the lack of traces.

**Comment by dineshg13** [comment]
@julealgon whats the size of the log you are trying to submit to Datadog ?

**Comment by julealgon** [comment]
> @julealgon whats the size of the log you are trying to submit to Datadog ?

How can I get that information @dineshg13 ? We have many projects currently sending log information through the collector, so I don't precisely know which particular source is sending potentially big logs that could be causing this error.

The logs from the exporter also don't mention anything about which payload is failing. I'd need help in identifying what payload is actually causing this problem.

**Comment by julealgon** [comment]
@dineshg13 can you confirm whether this might still be an issue or not?

**Comment by dineshg13** [comment]
@julealgon we have fixed this issue. Can you please try using latest collector-contrib image ?

**Comment by dineshg13** [comment]
@julealgon were u able to try this ?

**Comment by julealgon** [comment]
> @julealgon were u able to try this ?

I did update the collector a while ago and the problem seemed to go away.

**Comment by Lyndon-prequel** [comment]
I ran into this issue too...on an old collector.  To make it easier for others to figure out if they're affected, I created a common reliability enumeration (CRE). You can preview the rule [here](https://play.prequel.dev/?data=EwBmFYFoQFkhGcAVUAueB2V4AcA6cANhxhI0IE4AtAAhoFMAnRge0boEsA7AFya4CGAGwD0ARwCu9KQH0AzvS4ATJngDmLdCHB0AogA8ADmx7c1NAGYCOQ%2Bkrw0AIq0OGzNJQJ4CHSRgE8GQQAjIXdGeh4AmRYuGSsbCQiaAGNYiw5zFkNTWJoeFhoIqMC84oCBUPoGZjY5BxoAbwAiAGtuJWbUGmb6IxMmZoAaHs9vGR5-Q3ounoBbSMYOFLlhnsEF2eaWHiFDAAseHkM13trGLYAFJjmBLkUeGtZGbph4AGYaS4F-IRYBJQ0JAsQoAGQEjDUMxGzSULmmShkHD4c1W3XeOExAF8gA&rule=E4VwNgpgzgXAUAWgAQGNgXkrSCWATGJAYQCUBRBAJgAZKBWBa6gZgDY5skoIA3CYHABcAnoWYdsgoZEIB5AA4QAdgBUIkALYRBwYcQD2YSCkH7gSPMH3yoFgIaC7FkBCSmkAFgCMzJAAU7YTB9OzwkFX19JAAZO2AAc1cAMysNJAgAD3kzQX43OMTBCSwUBwh4s1EkfQAjbmAeOxqcMCFhBHkrGs1ipDsQQQALM0I-dABHFzBevGg0HHkpfSVCJAAfXqxkFUHXBWU1TW1dAyMIEzMkDUCLK3k3dQgtHT08BycAd12lPp-M7OAuXMNTsKAA1sowugoNklHhbB8hIM%2Bp4fP5AsFQuFIjECq5%2BFZgAA6cKDHC2ETyHClIx6QZ2eSKJQI75IMB4pAgwQoXa2fRJK7HalQAA0bP08VF1XMOlB0HSGRQEAgYSGrmuGRwGhAaXkGJCYSgOAAXq5QUrFirOXo1ZzQRC4SSAEKvCBJfpgQRi20oQzGUzmSzWCm81x6oIG2wgJSQKC2dAvTkQek8HCXckK%2BStFDSPTKJqQPBE3qlEDcQgbThbUmuEHgyFcfh8cwACggRPiRLFzwEKFsWYcSTMGjFtXqjWarRESD4cLMAEokAmQMAlFa7D8ABIqFR%2BVG%2BKCOQRlsXoABW5ykSnibl2SHDmLCdgpOPZCXbNczOTyvo0sOUggWPo8pKPogH9KY1xSDSYB6AmJzRrGtgAAbwcIAD6yzoe6LQrhAyG4LY%2BbdCqJIAIK2E40LgF6t6uG8jiEbc1iKGEijANca5KIIsHFpwjiSpgVbIGB6gIL6ZwXMAmxIMg-zftJVayfe%2BqhDJyBcjy6nMfI2ljk2TQtG02m5EcLzaWCoEfEoCDklALi9BoQg4PEDhpis6zaWQSgFq4qHHBhWE4WAeEETgPy2ugkCNNxX6Aj%2ByxJC5bhRHYRj6B8S4BeK8TUnxwlICQKogEqdrcsiRqmjOOBOMh3BwuF8ToZMEAuAR3CCFekrSnFQIIDC5w4ElKBIMhUhaPoAzIQA9MhSQhVAgzoeFQKNGABG%2BkoSXxCubnLFA%2BWcMgACq3BICANg6BAdhpFAN1Zo1PV2PE8ToK5SwRVE6B4CVYaqWEPCGDq7baQAaml%2BBlHa9Zwrg17QB9bJakIthth2XZXHYGTWrk-Z5BMLiHouG5Pq08R-FkClI05giUSgvrAHgjW8b06BJPwyhKrA2mDJ1NgwNN025UMIA1ESv7TdYygIKZTwBZLTKyz27QSf6ZjTd0tTTdc4XTfJ8XAHrlMG7sYDsdN5BkQAIgAsmQRIaHgPN87AgvC4Movi-oGgK9LSvy1L3GPMr4l%2Bpe6t2YT00ABzUF41C9AyD2lB93NKcgPlaIQgf%2By8oeSQGMlYM2RrLIQADkAB8AC81BErHRLUOXReoMsjjhfwAByN0YNUpn52rinYFqeomIQucnMEcbOK47jnpeVoPpGSApN7vV5LMh7hXtSi9CPoKCAAygzvfsJwNMuTvx9mL34icOgAK04QZ%2BCo4DF2EJWBguFBD3gT6h71-gATTiEoAAnFbAAYlbPwzBo7R2AGCEgrAah0EoIfUGu9OD0kWoQTcghjQZEGC9D4EBmA8EEEQAAikQZgAB1Y6JAiBEG3K9Y6HgADSh8ahkUGHQqhQCbYqH4WeeIRBD5UN6IkDyXgJCgBkL0Dqn9sC8AAsozgUBJrACVIQNA7ZgidhzsHAKA9w5D3Pg4Hk6jsDIDepkCuK1%2BA%2BTANNFqLh0L1VmMSAAVGQY2XUV52BaKRbxAAifWQJQlEm8X4fgnEALpGAISQg3hfABAjFiCIURYjvmieXIAA) or run it against your logs [here](https://github.com/prequel-dev/preq).
