### ISSUE TITLE
Bump github.com/aerospike/aerospike-client-go/v6 from 6.13.0 to 6.14.0 causes issues

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector-contrib#26265]
### Component(s)

receiver/aerospike

### Describe the issue you're reporting

See https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/6015671753/job/16318410285?pr=26262 for more details:

```
go: downloading github.com/mattn/go-sqlite3 v2.0.3+incompatible
mkdir -p /home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/coverage/unit
go test -race -timeout 300s -parallel 4 --tags="" -cover ./... -covermode=atomic -args -test.gocoverdir="/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/coverage/unit"
# github.com/mattn/go-sqlite3
sqlite3-binding.c: In function ‘sqlite3SelectNew’:
sqlite3-binding.c:128049:10: warning: function may return address of local variable [-Wreturn-local-addr]
128049 |   return pNew;
       |          ^~~~
sqlite3-binding.c:128009:10: note: declared here
128009 |   Select standin;
       |          ^~~~~~~
panic: proto: file "rpc/rpc.proto" has a name conflict over DEFAULT
	previously from: "github.com/aerospike/aerospike-client-go/v6/proto/kvs"
	currently from:  "github.com/checkpoint-restore/go-criu/v5/rpc"
See https://protobuf.dev/reference/go/faq#namespace-conflict
```

**Comment by antonblock** [comment]
https://github.com/aerospike/aerospike-client-go/issues/414

**Comment by crobert-1** [comment]
Looks like this is a valid issue in the dependency so I'll remove the `needs-triage` label.

/label -needs-triage

**Comment by djaglowski** [comment]
I'll take a look at this.

**Comment by djaglowski** [comment]
@dwelch-spike, any ideas?

**Comment by dwelch-spike** [comment]
@djaglowski I'll bring the proto name issue up with the Go client developer, @khaf.

**Comment by TylerHelmuth** [comment]
I think this will get resolved with https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/30261, which requires use to bump our go version to 1.21

**Comment by khaf** [comment]
I'll try to backport most of the Aerospike Go Client v7 changeset to the v6. Hopefully that will resolve this ticket.

**Comment by khaf** [comment]
This issue should be addressed in the Go client v6.15.0. Let me know how it goes.

**Comment by TylerHelmuth** [comment]
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/30785

**Comment by khaf** [comment]
I now see what's going on. The manifest used for the Aerospike Proxy Server does not state a package name, in effect using the Global Namespace. That's unfortunate, since it is not in my control. I'll ask my colleagues to address the issue. In the mean time, I'll see if I can provide a build flag to exclude the Proxy server during build.

**Comment by TylerHelmuth** [comment]
@khaf got the same error when using v7: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/31270

**Comment by TylerHelmuth** [comment]
Still experiencing problems with bumps to v6.15.1 and v7.4.0 after configschema was removed:

- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/33394
- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/33392

**Comment by djaglowski** [comment]
Closing in favor of https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/34244
