### ISSUE TITLE
[exporter/prometheusremotewrite] Exporter sending un-ordered samples when WAL is enabled

### ISSUE THREAD

**Issue by MichaelThamm** [open-telemetry/opentelemetry-collector-contrib#41785]
### Component(s)

exporter/prometheusremotewrite

## Description

According to [this related PrometheusRemoteWrite (PRW) issue](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/39080), the [WAL has been "broken for years"](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/39080#issuecomment-2839664000). This is evident when the PRW exporter tries to write to the `/api/v1/write` Prometheus API and received a `400 - Bad Request` response due to "error processing WAL entries" causing "Permanent error: out of order sample" and eventually "out of bounds". When removing the WAL config from the PRW exporter:

```diff
exporters:
  prometheusremotewrite/0:
    endpoint: http://prom-0.prom-endpoints.how-to.svc.cluster.local:9090/api/v1/write
    tls:
      insecure_skip_verify: false
-   wal:
-     directory: /otelcol
```

Then the issue is resolved.

## Steps to Reproduce

We use Juju to deploy our infra:
- https://github.com/canonical/opentelemetry-collector-k8s-operator/issues/105

TL;DR Deploy a metrics source (e.g. Alertmanager), deploy a metrics sink (e.g. Prometheus) and configure them in the otel-collector receivers and exporters.

## Expected Result
Metrics arrive in Prometheus with a working WAL.

## Actual Result
Metrics arrive in Prometheus, but there are errors hinting at a broken WAL in the otel-collector logs.

### Collector version

0.130.1

## Environment
OS: `Ubuntu 24.04.2 LTS`

### OpenTelemetry Collector configuration

```yaml
connectors: {}
exporters:
  debug:
    verbosity: basic
  prometheusremotewrite/0:
    endpoint: http://prom-0.prom-endpoints.how-to.svc.cluster.local:9090/api/v1/write
    tls:
      insecure_skip_verify: false
    wal:
      directory: /otelcol
extensions:
  file_storage:
    directory: /otelcol
  health_check:
    endpoint: 0.0.0.0:13133
processors:
  attributes:
    actions:
      - action: upsert
        key: loki.attribute.labels
        value: container, job, filename, juju_application, juju_charm, juju_model, juju_model_uuid, juju_unit, snap_name, path
  resource:
    attributes:
      - action: insert
        key: loki.format
        value: raw
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  prometheus:
    config:
      scrape_configs:
        - job_name: juju_how-to_7b30903e_otelcol_self-monitoring
          scrape_interval: 60s
          static_configs:
            - labels:
                instance: how-to_7b30903e_otelcol_otelcol/0
                juju_application: otelcol
                juju_charm: opentelemetry-collector-k8s
                juju_model: how-to
                juju_model_uuid: 7b30903e-8941-4a40-864c-0cbbf277c57f
                juju_unit: otelcol/0
              targets:
                - 0.0.0.0:8888
        - job_name: juju_how-to_7b30903e_am_prometheus_scrape
          metrics_path: /metrics
          relabel_configs:
            - regex: (.*)
              separator: _
              source_labels:
                - juju_model
                - juju_model_uuid
                - juju_application
              target_label: instance
          scheme: http
          static_configs:
            - labels:
                juju_application: am
                juju_charm: alertmanager-k8s
                juju_model: how-to
                juju_model_uuid: 7b30903e-8941-4a40-864c-0cbbf277c57f
              targets:
                - am-0.am-endpoints.how-to.svc.cluster.local:9093
          tls_config:
            insecure_skip_verify: false
service:
  extensions:
    - health_check
    - file_storage
  pipelines:
    logs:
      exporters:
        - debug
      processors:
        - resource
        - attributes
      receivers:
        - otlp
    metrics:
      exporters:
        - prometheusremotewrite/0
      receivers:
        - otlp
        - prometheus
    traces:
      exporters:
        - debug
      receivers:
        - otlp
  telemetry:
    logs:
      level: DEBUG
    metrics:
      level: normal
```

### Log output

```shell
2025-08-05T14:11:50.231Z [otelcol] 2025-08-05T14:11:50.231Z     error   prw.wal prometheusremotewriteexporter@v0.130.0/wal.go:245    error processing WAL entries    {"resource": {"service.instance.id": "00ba5573-5bb4-4294-b1ca-1f84b32dbf29", "service.name": "otelcol", "service.version": "0.130.1"}, "otelcol.component.id": "prometheusremotewrite/0", "otelcol.component.kind": "exporter", "otelcol.signal": "metrics", "error": "Permanent error: Permanent error: Permanent error: remote write returned HTTP status 400 Bad Request; err = %!w(<nil>): out of order sample\n; Permanent error: Permanent error: Permanent error: remote write returned HTTP status 400 Bad Request; err = %!w(<nil>): out of order sample\n; Permanent error: Permanent error: Permanent error: remote write returned HTTP status 400 Bad Request; err = %!w(<nil>): out of order sample\n", "errorCauses": [{"error": "Permanent error: Permanent error: Permanent error: remote write returned HTTP status 400 Bad Request; err = %!w(<nil>): out of order sample\n"}, {"error": "Permanent error: Permanent error: Permanent error: remote write returned HTTP status 400 Bad Request; err = %!w(<nil>): out of order sample\n"}, {"error": "Permanent error: Permanent error: Permanent error: remote write returned HTTP status 400 Bad Request; err = %!w(<nil>): out of order sample\n"}]}
```

### Tip

<sub>[React](https://github.blog/news-insights/product-news/add-reactions-to-pull-requests-issues-and-comments/) with 👍 to help prioritize this issue. Please use comments to provide useful context, avoiding `+1` or `me too`, to help us triage it. Learn more [here](https://opentelemetry.io/community/end-user/issue-participation/).</sub>

**Comment by ArthurSens** [comment]
> According to [this related PrometheusRemoteWrite (PRW) issue](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/39080), the [WAL has been "broken for years"](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/39080#issuecomment-2839664000). This is evident when the PRW exporter tries to write to the `/api/v1/write` Prometheus API and received a `400 - Bad Request` response due to "error processing WAL entries" causing "Permanent error: out of order sample" and eventually "out of bounds". When removing the WAL config from the PRW exporter:

Hey 👋 , yes it was broken for years but it [was fixed in January](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/37630). Before that, the WAL would enter a deadlock and would literally never send anything, and would not send any error messages. I did test what you described in the issue and I could reproduce the error you mention, I just wanted to clarify that I meant a different thing in that comment :)

A simpler setup can produce the same behavior and error messages, for those who might want to try fixing this!

OTel config file:
```yaml
receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: 'otelcol'
          scrape_interval: 15s
          static_configs:
            - targets: ['localhost:8888']

exporters:
  prometheusremotewrite:
    endpoint: http://localhost:9090/api/v1/write
    wal:
      directory: ./wal

service:
  pipelines:
    metrics:
      receivers: [prometheus]
      exporters: [prometheusremotewrite]
  telemetry:
    metrics:
      readers:
        - pull:
            exporter:
              prometheus:
                host: '0.0.0.0'
                port: 8888
```

And you can start a prometheus server with this cmdline:
```console
$ ./prometheus --config.file my-empty-yaml-file.yml --web.enable-remote-write-receiver
```

The errors I'm seeing are very accurate with what has been described, and I'm seeing a steady memory increase in my collector

**Comment by ArthurSens** [comment]
Just to document a workaround. If you enable out-of-order ingestion in the Prometheus instance who is receiving the remote write request, this error goes away.
https://prometheus.io/docs/prometheus/latest/configuration/configuration/#tsdb

**Comment by MichaelThamm** [comment]
> Just to document a workaround. If you enable out-of-order ingestion in the Prometheus instance who is receiving the remote write request, this error goes away. [prometheus.io/docs/prometheus/latest/configuration/configuration#tsdb](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#tsdb)

Do you mean the `out_of_order_time_window`?

**Comment by ArthurSens** [comment]
yes, exactly

**Comment by kgeckhart** [comment]
I linked #42222 to this ticket which includes some doc updates to note that OOTB WAL might cause out of order. The default concurrency when writing requests is 5. Changing it 1 doesn't fix the issue with out of order writes though. I'm hoping to make some more time this week to try to get to the bottom of it because it's rather strange behavior.

**Comment by MichaelThamm** [comment]
Hi @kgeckhart,

Do you have any updates on this?

**Comment by kgeckhart** [comment]
@MichaelThamm took a little longer than expected to make the time and get to the bottom of it but #44467 should do it.

**Comment by MichaelThamm** [comment]
Amazing, thanks for the link! I will keep an eye out for it to merge.
