### ISSUE TITLE
Change of Couchbase Metric Collection Method

### ISSUE THREAD

**Issue by armstrmi** [open-telemetry/opentelemetry-collector-contrib#9254]
**Is your feature request related to a problem? Please describe.**

The way that Couchbase metric receiver is currently set up is to scrape the REST API as the method of metric collection. This API has some caveats though as it returns arrays of data points over the last minute and most of them are precomputed rate metrics. Using this API it's not possible to grab the raw counter metrics that would be more desireable. It's also possible to cause aliasing if we don't reconcile the array of data points that is returned during a collection.

The team at ObservIQ spoke with Couchbase SRE's to learn how they monitor Couchbase and how they tell their customers to do so. They pointed at the embedded prometheus server that was added in Couchbase 7.0. They even pointed us to an in house [program](https://github.com/couchbaselabs/cmos-prometheus-exporter) that forward ports metrics from 6.x versions to the 7.0 format. The prometheus server exposes the raw counter metrics that we would prefer.

**Describe the solution you'd like**

Remove the REST client code and models from the Couchbase metric receiver in favor of refactoring the code to wrap the Prometheus receiver that is flavored for Couchbase. 

There is an argument for just using the prometheus receiver but we feel wrapping the prometheus receiver gives a better customer experience. It allows us to "curate" the experience by limiting what is required for the internal prometheus config to only things that are relevant to Couchbase. We also gain the advantage of using the metric builder to filter out only KPIs and convert them from the, not always obvious, prometheus names into a metric that is clear to the customer with attributes that are appropriate for monitoring Couchbase.

There is a precedent set of wrapping receivers with the recent work done with wrapping the Windows Performance Counter Receiver for [IIS](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/8832).

**Comment by cpheps** [comment]
I'm work with @armstrmi on this and am in favor of removing the original REST API client code I wrote and wrapping the prometheus receiver.

We're looking to see if the community see's any issues with this or if this is an acceptable way to move forward and get a couchbase receiver into the collector.

**Comment by djaglowski** [comment]
Withholding my opinion on this for a moment, a few thoughts about the process:
- I am the sponsor of this component but it hasn't yet been implemented as originally proposed. Since this is proposing a very different approach, I think it akin to a proposal for a new component, so requires sponsorship to be reestablished.
- If the approach is not accepted or if no sponsor is found, then I think the incomplete codebase should be removed as well.

Questions on the proposed approach:

> It allows us to "curate" the experience by limiting what is required for the internal prometheus config to only things that are relevant to Couchbase.

Will you elaborate on what specifically would be different in the config? 

> convert them from the, not always obvious, prometheus names into a metric that is clear to the customer with attributes that are appropriate for monitoring Couchbase.

Can you provide a couple examples? This could be valuable, but it would be good to understand what you're seeing as deficient in the prometheus model.

> We also gain the advantage of using the metric builder to filter out only KPIs...
>
> There is a precedent set of wrapping receivers with the recent work done with wrapping the Windows Performance Counter Receiver for https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/8832.

The collector _is_ designed to allow encapsulation of components, but the IIS implementation ended up _not_ wrapping the Windows Performance Counter receiver, primarily due to the difficultly in integrating the metrics builder. The initial implementation _ran_ the receiver, but the internal WPC receiver emitted metrics directly to the pipeline, which meant that the IIS receiver did not have the ability to apply the metrics builder. In the end, a library was extracted from the WPC receiver and shared by generic and specific receivers. 

With the above in mind, can you determine if there is a way to share code with the prometheus receiver, such that there is an opportunity to process the data that's been received before emitting it from the receiver?

**Comment by cpheps** [comment]
@djaglowski I can answer the first two questions.

> Will you elaborate on what specifically would be different in the config?

So this is mostly just pairing down what is presented to he user. The scraper config has a lot of options for users and if you're not familiar with Prometheus it can be overwhelming. For Couchbase a vast majority of those options are not applicable so we can omit them. 

Authorization is a good example, there are several options in Prometheus to authenticate. Couchbase on the other hand only has Basic Auth with user/pass so we would only present a `username` and `password` fields to the user rather than the `basic_auth` section of the Prometheus `scraper_config`.

> Can you provide a couple examples? This could be valuable, but it would be good to understand what you're seeing as deficient in the prometheus model.

Here is a sample of some of the metrics we want to collect with their Prometheus names and what we would map them to in order to provide better context to the user.

| Prometheus Metric | Renamed Couchbase Metric |
| :-- | :-- |
| kv_vb_curr_items | bucket.item.count |
| kv_ops | bucket.operation.count |
| kv_ep_tmp_oom_errors | bucket.error.oom.count (error_type = recoverable) |

If you are a Couchbase power user you will likely know which metrics you want to monitor and what they are. Otherwise it's unlikely you could look at the Prometheus output and find the metrics you're looking for. Most of the prometheus metrics do not have descriptions or namespaces to assist either.

**Comment by BinaryFissionGames** [comment]
Hey @djaglowski, circling back on this with a proposal here -

> Will you elaborate on what specifically would be different in the config?

I'd propose a config with these options:

```yaml
receivers:
  couchbase:
    endpoint: http://localhost:8901
    username: otelu
    password: otelp
    collection_interval: 10s
      metrics:
        couchbase.bucket.operation.count:
          enabled: false
```

This config would scrape http://localhost:8901/metrics for prometheus metrics (this would be the default)

This is significantly reduced/simplified from the config of the prometheus exporter, and much easier to configure scraping from couchbase.

> Can you provide a couple examples? This could be valuable, but it would be good to understand what you're seeing as deficient in the prometheus model.

@cpheps already provided some good examples - the prometheus metric names aren't particularly understandable to someone who's not a power-user. There's certainly a benefit to having a well named and described subset of key metrics that are emitted from a receiver.

> The collector _is_ designed to allow encapsulation of components, but the IIS implementation ended up _not_ wrapping the Windows Performance Counter receiver, primarily due to the difficultly in integrating the metrics builder. The initial implementation _ran_ the receiver, but the internal WPC receiver emitted metrics directly to the pipeline, which meant that the IIS receiver did not have the ability to apply the metrics builder. In the end, a library was extracted from the WPC receiver and shared by generic and specific receivers.

I'd consider both options here; Let me know which one you think is preferable:

1. Run the prometheus receiver internally
   - It is completely possible to receive the metrics emitted by the receiver and process them, we just need to create an internal metrics consumer and pass it to the receiver. This internal metrics consumer would pass metrics to the actual consumer after using the metrics builder to re-emit the metrics.
   - Upside is that very little work would need to be done to actually scrape the prometheus metrics.
   - Downside is that a translation layer is needed to re-emit the metrics using the metrics builder in the correct format, which can be verbose.
2. Extract out the [appender](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/39a694e1f8e9f1c828bf6b1e75c96b269d089bae/receiver/prometheusreceiver/internal/appendable.go#L29) ([Documentation on this here](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/prometheusreceiver/DESIGN.md#implementing-prometheus-storageappender-with-metrics-sink)) from the prometheus receiver into a shared package. This acts as the metric sink that emits translated metrics from prometheus. 
	- Upside to this is not having to run the receiver itself inside another receiver.
	- Downside is that I don't think this is actually really all that different from running the receiver inside another. The appender emits metrics over a consumer, which is essentially the same output interface we have when running the receiver nested. We would still need a translation layer from the emitted metrics to the metric builder. The code outside of this portion is also pretty small, so I don't think we really gain all that much by doing this.
3. Extract out the appender, and try to genericize it so that we can get the "raw", unconverted prometheus metrics instead of pdata converted metrics.
    - The existing appender has all sorts of concerns it takes care of with metrics (these are pointed out in the prometheus receiver's DESIGN.md), so I don't think we want to try and roll our own simplified version, but we'd want to use the underlying transaction without the metric builder.
    - Upside is that we can ditch the general conversion layer and only convert the specific metrics we care about.
    - Downside is it'll still probably be verbose, and probably not even that dissimilar to \# 1 & \# 2. This is also the largest effort of our options, and I'm not sure if the benefit really outweighs the effort.

I think in the instance of the windowsperfcounters, it made sense to pull the logic into it's own package and use that, since you had the ability to scrape a specific metric's raw datapoint and that's very easy to encapsulate in a single interface, but it's much more difficult to do the same with how prometheus works with its appendable interface, which is more of a callback based API - somewhat similar to the API the receivers in OTel themselves provide.

Personally, I lean towards \# 1, due to the lower effort, and the fact that it really doesn't seem all that different as to how the couchbase receiver itself would look with these other options.

**Comment by djaglowski** [comment]
Thanks for the additional details @BinaryFissionGames. This is probably worth discussing in the Collector SIG tomorrow, if you can make it. I'm not a prometheus expert, so maybe some others there can help evaluate the proposal.

> This is significantly reduced/simplified from the config of the prometheus exporter

Just to clarify, doesn't the user still need to configure a prometheus exporter in addition to this receiver? Did you mean to say this receiver would be simpler than the prometheus receiver?

**Comment by BinaryFissionGames** [comment]
> Just to clarify, doesn't the user still need to configure a prometheus exporter in addition to this receiver? Did you mean to say this receiver would be simpler than the prometheus receiver?

Right, that's what I meant, oops.

An exporter needs to be configured for v6.x and below, couchbase has a prometheus endpoint by default as of v7.0:
https://docs.couchbase.com/operator/current/howto-prometheus.html#couchbase-prometheus-endpoint
```
As of Couchbase Server 7.0, a metric endpoint exists on each Couchbase Pod that is compatible with Prometheus metric collection. This endpoint exists by default and does not require any configuration within the CouchbaseCluster resource to begin receiving metrics into Prometheus.
```

I'll bring it up at the SIG tomorrow.

**Comment by BinaryFissionGames** [comment]
So, here's what I've come up with so far:

```yaml
receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: 'couchdb'
          scrape_interval: 10s
          static_configs:
            - targets: ['127.0.0.1:8091']
          basic_auth:
            username: otelu
            password: otelpassword

processors:
  filter:
    metrics:
      include:
        match_type: strict
        metric_names:
          - kv_ops
          - kv_vb_curr_items
          - kv_num_vbuckets
          - kv_ep_cursor_memory_freed_bytes
          - kv_total_memory_used_bytes
          - kv_ep_num_value_ejects
          - kv_ep_mem_high_wat
          - kv_ep_mem_low_wat
          - kv_ep_tmp_oom_errors
          - kv_ep_oom_errors

  metricstransform:
    transforms:
      - include: kv_ops
        match_type: strict
        action: update
        new_name: "couchbase.bucket.operation.count"
      - include: kv_vb_curr_items
        match_type: strict
        action: update
        new_name: "couchbase.bucket.item.count"
      - include: kv_num_vbuckets
        match_type: strict
        action: update
        new_name: "couchbase.bucket.vbucket.count"
      - include: kv_ep_cursor_memory_freed_bytes
        match_type: strict
        action: update
        new_name: "couchbase.bucket.memory.usage.free"
      - include: kv_total_memory_used_bytes
        match_type: strict
        action: update
        new_name: "couchbase.bucket.memory.usage.used"
      - include: kv_ep_num_value_ejects
        match_type: strict
        action: update
        new_name: "couchbase.bucket.item.ejection.count"
      - include: kv_ep_mem_high_wat
        match_type: strict
        action: update
        new_name: "couchbase.bucket.memory.high_water_mark.limit"
      - include: kv_ep_mem_low_wat
        match_type: strict
        action: update
        new_name: "couchbase.bucket.memory.low_water_mark.limit"
      - include: kv_ep_tmp_oom_errors
        match_type: strict
        action: update
        new_name: "couchbase.bucket.error.oom.count.recoverable"
      - include: kv_ep_oom_errors
        match_type: strict
        action: update
        new_name: "couchbase.bucket.error.oom.count.unrecoverable"
      - include: '^couchbase\.bucket\.error\.oom\.count\.(?P<error_type>unrecoverable|recoverable)$$'
        match_type: regexp
        action: combine
        new_name: "couchbase.bucket.error.oom.count"
      - include: '^couchbase\.bucket\.memory\.usage\.(?P<state>free|used)$$'
        match_type: regexp
        action: combine
        new_name: "couchbase.bucket.memory.usage"


exporters:
  logging:
    loglevel: debug

service:
  pipelines:
    metrics:
      receivers: [prometheus]
      processors: [filter, metricstransform]
      exporters: [logging]
```

This is MOSTLY there, there are 3 issues right now that make this troublesome:
1. The metric descriptors are missing descriptions
2. The metric descriptors are missing units
3. The metrics are marked as gauges, but some of them should be sums (e.g. bucket.operation.count). 

From what I'm aware of, there are no components currently in the collector to handle these cases.
It looks like the transform processor may be able to handle the first two when metrics support is added, but I'm not sure about number 3 (it seems like it _could_ also be supported with the transform processor).

**Comment by djaglowski** [comment]
> 3 issues right now that make this troublesome:
> 
> 1. The metric descriptors are missing descriptions
> 2. The metric descriptors are missing units
> 3. The metrics are marked as gauges, but some of them should be sums (e.g. bucket.operation.count).

@dashpole, do you think any of these _should_ be handled by the prometheus receiver?

**Comment by dashpole** [comment]
It sounds like there are 3 issues:

1. Missing descriptions
2. Missing units
3. Missing types

All three indicate missing metric [metadata](https://github.com/prometheus/docs/blob/main/content/docs/instrumenting/exposition_formats.md#comments-help-text-and-type-information) on the couchbase endpoint, and should be fixed in couchbase's prometheus endpoint.  We can't fix this in the prometheus receiver, but could wrap the prometheus receiver as we had discussed.

**Comment by djaglowski** [comment]
Thanks for the clarification.

If this were just an issue of needing to add units and descriptions, I'd say we just enhance the metricstransform or transform processor. However, it's not clear to me that these processors should support data type manipulations.

Any thoughts on this @TylerHelmuth, @bogdandrutu?

**Comment by BinaryFissionGames** [comment]
@TylerHelmuth @bogdandrutu - just re-pinging in case you missed this; Any thoughts on whether the transform processor will or should allow for datatype (e.g. gauge -> sum) manipulations on metrics?

**Comment by BinaryFissionGames** [comment]
Discussed metric datatype manipulations at the SIG today.
The transform processor does not currently support converting between scalar metric datatypes, but support will be added and is tracked in #10130.

Once this functionality is added, we should be able to make a config, and then it becomes a question of how to distribute/contribute configs like this.

**Comment by TylerHelmuth** [comment]
Sorry I missed this mention.

Setting metric description and metric name is now supported by the transform processor using the `set` function like:

`set(metric.unit, "a unit")`

If you have a way to differentiate between metrics from this receiver and other receivers you can add a condition for when to call `set`

`... where metric.name = "specific metric name, wildcards are not yet supported"  

Otherwise you'll probably need the receiver to be in its own pipeline so that you can send all metrics through the `set` function.

**Comment by BinaryFissionGames** [comment]
@djaglowski I have a config that scrapes Couchbase now, and everything with it seems to be working fine now that #10255 is merged.

I think the final thing to do here is to contribute the config somehow. Would it be acceptable to add this as an example [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/examples)?

**Comment by djaglowski** [comment]
@BinaryFissionGames that seems reasonable to me.

**Comment by djaglowski** [comment]
The example config has been added but I'd like to keep this issue open until the incomplete original implementation has been removed.

**Comment by BinaryFissionGames** [comment]
@djaglowski I believe that #10482 removed the receiver stub, so in addition with #10894 being merged, I think we should be good to close the issue now!

**Comment by djaglowski** [comment]
Ah, good call. I forgot about that. Closing this then.
